ESERCIZIO PRE-ESAME.vecchio database.EsercizioEsame/EsercizioEsame/Controllers/LibriController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EsercizioEsame.Models;

namespace EsercizioEsame.Controllers
{
    public class LibriController : Controller
    {
        private PrestitiBibliotecaEntities db = new PrestitiBibliotecaEntities();

        // GET: Libri
        public ActionResult Index(string SearchString, string DropSearch)
        {
            if(SearchString == null || SearchString ==  "")
            { return View(db.Libro.ToList()); }

            else
            {
                var Books = db.Libro.ToList();
                if(DropSearch == "AUTORE")
                {
                    Books = Books.Where(x => x.Autore == SearchString).ToList();
                }
                if (DropSearch == "TITOLO")
                {
                    Books = Books.Where(x => x.Titolo == SearchString).ToList();
                }
                if (DropSearch == "EDITORE")
                {
                    Books = Books.Where(x => x.Editore == SearchString).ToList();
                }

                return View(Books); 
            }
            
        }

        // GET: Libri/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Libro libro = db.Libro.Find(id);
            if (libro == null)
            {
                return HttpNotFound();
            }
            return View(libro);
        }

        // GET: Libri/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Libri/Create
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Codice,Autore,Titolo,Editore,Anno,Luogo,Pagine,Classificazione,Collocazione,Copie")] Libro libro)
        {
            if (ModelState.IsValid)
            {
                db.Libro.Add(libro);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(libro);
        }

        // GET: Libri/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Libro libro = db.Libro.Find(id);
            if (libro == null)
            {
                return HttpNotFound();
            }
            return View(libro);
        }

        // POST: Libri/Edit/5
        // Per la protezione da attacchi di overposting, abilitare le proprietà a cui eseguire il binding. 
        // Per altri dettagli, vedere https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Codice,Autore,Titolo,Editore,Anno,Luogo,Pagine,Classificazione,Collocazione,Copie")] Libro libro)
        {
            if (ModelState.IsValid)
            {
                db.Entry(libro).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(libro);
        }

        // GET: Libri/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Libro libro = db.Libro.Find(id);
            if (libro == null)
            {
                return HttpNotFound();
            }
            return View(libro);
        }

        // POST: Libri/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Libro libro = db.Libro.Find(id);
            db.Libro.Remove(libro);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ESERCIZIO PRE-ESAME.vecchio database.EsercizioEsame/EsercizioEsame/Views/Libri/Create.cshtml
@model EsercizioEsame.Models.Libro

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Libro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Autore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Titolo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titolo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titolo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Editore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Editore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Editore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Luogo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Luogo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Luogo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pagine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pagine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pagine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Classificazione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Classificazione, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Classificazione, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Collocazione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Collocazione, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Collocazione, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Copie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Copie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Copie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ESERCIZIO PRE-ESAME.vecchio database.EsercizioEsame/EsercizioEsame/Views/Libri/Delete.cshtml
@model EsercizioEsame.Models.Libro

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Libro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Autore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autore)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titolo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titolo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Editore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Editore)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Luogo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Luogo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pagine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pagine)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Classificazione)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Classificazione)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Collocazione)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Collocazione)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Copie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Copie)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ESERCIZIO PRE-ESAME.vecchio database.EsercizioEsame/EsercizioEsame/Views/Libri/Details.cshtml
@model EsercizioEsame.Models.Libro

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Libro</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Autore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Autore)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titolo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titolo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Editore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Editore)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Anno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Anno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Luogo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Luogo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Pagine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Pagine)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Classificazione)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Classificazione)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Collocazione)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Collocazione)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Copie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Copie)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Codice }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ESERCIZIO PRE-ESAME.vecchio database.EsercizioEsame/EsercizioEsame/Views/Libri/Edit.cshtml
@model EsercizioEsame.Models.Libro

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Libro</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Codice)

        <div class="form-group">
            @Html.LabelFor(model => model.Autore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Autore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Autore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Titolo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titolo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titolo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Editore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Editore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Editore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Anno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Anno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Anno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Luogo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Luogo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Luogo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pagine, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pagine, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pagine, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Classificazione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Classificazione, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Classificazione, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Collocazione, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Collocazione, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Collocazione, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Copie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Copie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Copie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ESERCIZIO PRE-ESAME.vecchio database.EsercizioEsame/EsercizioEsame/Views/Libri/Index.cshtml
@model IEnumerable<EsercizioEsame.Models.Libro>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Libri", FormMethod.Get))
{
    
        List<SelectListItem> listDrop = new List<SelectListItem>();
        listDrop.Add(new SelectListItem
        {
            Text = "Autore",
            Value = "AUTORE"
        });
        listDrop.Add(new SelectListItem
        {
            Text = "Titolo",
            Value = "TITOLO",
            Selected = true
        });
        listDrop.Add(new SelectListItem
        {
            Text = "Editore",
            Value = "EDITORE"
        });
    

    @Html.DropDownList("DropSearch", listDrop, new { @class = "form-control" })

    @*INPUTBOX*@
    @Html.TextBox("SearchString")
    <input type="submit" value="Search" />

}




</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Autore)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Titolo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Editore)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Anno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Luogo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Pagine)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Classificazione)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Collocazione)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Copie)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Autore)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Titolo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Editore)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Anno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Luogo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pagine)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Classificazione)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Collocazione)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Copie)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Codice }) |
                @Html.ActionLink("Details", "Details", new { id = item.Codice }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Codice })
            </td>
        </tr>
    }

</table>